service: gsmendoza_site
image: gsmendoza/gsmendoza_site

servers:
  web:
    - gsmendoza.name

proxy:
  ssl: true
  host: gsmendoza.name

registry:
  username: gsmendoza

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "gsmendoza_site_storage:/rails/storage"
  - "gsmendoza_site_sqlite:/rails/db/production.sqlite3"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: gsmendoza

